repoURL: https://gitlab.com/azwickey/tanzu-pez.git
todosRepo: https://gitlab.com/azwickey/todos.git
targetRevision: HEAD
server: https://kubernetes.api.lb:6443  # This must be overridden
ingress:
  ingressFQDN: '*.cloud.zwickey.net'
  email: azwickey@vmware.com
harbor:
  domain: registry.cloud.zwickey.net
  pwd: topSecret # This must be overridden
prometheus:
  ingressFQDN: prometheus.cloud.zwickey.net
grafana:
  ingressFQDN: grafana.cloud.zwickey.net
  pwd: topSecret # This must be overridden
kubeapps:
  domain: catalog.cloud.zwickey.net
dex:
  ingressFQDN: dex.cloud.zwickey.net
  clientId: 0oaagkq37j5IEbOqe4x6
  clientSecret: topSecret # This must be overridden
  idpUrl: https://dev-104945.okta.com/oauth2/default
  # This is simply the acme CA
  ca: H4sIAL+zgF8AA2WVSfOquhbF53yKO7dOiSCIgzNIIDR/DErfzOikFxUlwKd/6Ht13617MmPXprKy9volv36tCyJFM/4SkeVosiYCB32KvyisaaipRRGwjwIQDYJCM8VChmYBAPDOcsr0pzKfb6IEDFg0j7KplCOhITAHGUhgS2HbJFoRSp5p6mh6odjP7pkiD5ps3COGKzPVmyMbuunNWzIRSsm8n+QFeLAwPAiwQ0mN5XgitBPmSGvIgJpcLBjuA8lBDJbwZCyIMSRAG22/1rTpXzVC2TU6YdAoYOciWGLR8/Ak18D97w69I7lTm4nZoiHvHbI/XKqak7aA8m8FSvNHQ2EGHh0rxzkOLO6rSNOgVv/bAyQDcBYpYArg0yAWurgWwc3AWJCf7anJ2bSl2eJg9OEiPXaL2yl2UI7JficEon065HubRjL14LvcMMvwcEKPSalUkb/UWe50Ap9VaXLnCh9cd5wS37YXM1eyaVaacxupl+07jngfCJSNp83c7FhU2Zk1vWL+cBvUOgXqzzzkfCrzA6fzhx3knDh8p+MxcWY/NoRab3RT0iKaioRye48ee7dDLlqOLR/q6nwcealNmLK/LaWzCcrHhrDwOcaE8eQbi3QetsO9QcbNB1TMT7owvU07KMb+Hl30CrS66SgZlkycMhfsVJ78fPT4UEpCgq5kgdv+1kxooV/GWNfU9qIt8bPhcOqPk0Ybqm/6mH/ypdgxOzACRmWlhmgSMAHs9xq8Omtqg4agT/gs2lmnoG7X/BJYILj9RFkC58+MVVOA4CqgddYiCENyJaGmkxBC01XXaaF0gWuoNIUSxUEBpivDBcCyivpMtci5EsY4MOZo5uhvhJW2OXXHOmXBO/atNrlZcxYY9KkzRipxwAEWxXNVsBKUEtCHY6xadCr144mRSariP35K7OP8iX46HxsqZa3vR8jIezxzxGAwUcn3fDWEBZF74E56Pt3VYUivz2Tvvs3sukWyL8qVBQjlgW9zARFN7AVosIhuhUlWWxC5kPD0PTdQRHbCn/gSLIH3PxSvUbbC6v+SDZLO3FfRKSimU7dyohpt0hlzHsBV/nGOFiB8TbYEZDhgobCkFCcevMrq9beBK1TDqWubyP+fiSJXJww9WrLhus3x4q3Y+5IhuQ15U59mDOkPzplUmD6Edm939xqqbPZ+J9Y5yTvLD0aBr4fe+fNWoj5IfihknUuArkbtS3WmwOAgev4ma2MuRVUbr/dRLmiN+HOa/PKoo6phf1TLUpWfnnpjxkuVa3vkbcGpSmuJxv7Z5xn/qnj/gWD3Wgjr91n8KjbefM7v5R6F9+d2RwL9NQlbioC7Nv7Y5NV51R7LLhfjx9OWEJ/HBxbXzCvFc8/VOOPrLvddVReGflv3vturZ7dYPQj2l35nhsuGzYalkR74vr827QRJYA3+jtaDZeUp2gznCxjzeapuWVc3vtAq88YcrFahLtdoo/ARXx66Ou/ocFP5bROm3v6i+addRWAlDLGYKDZXG8xdwJtgYx5cQ0fN6i9r8JR+fjSPjjs46spdLv2Axr6V/FYy5DdtFr9/U9/nAxnSn0/KfwAwReCybwYAAA==
