apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
 name: shared-services
 namespace: ss
spec:
 distribution:
   version: v1.18.5
 topology:
   controlPlane:
     count: 3 #3 control plane nodes
     class: best-effort-medium #large size VM
     storageClass: cloud-storage #Specific storage class for control plane
   workers:
     count: 3 #5 worker nodes
     class: best-effort-xlarge #extra large size VM
     storageClass: cloud-storage #Specific storage class for workers
 settings:
   network:
     cni:
       name: calico
     services:
       cidrBlocks: ["198.51.100.0/12"] #Cannot overlap with Supervisor Cluster
     pods:
       cidrBlocks: ["192.0.2.0/16"] #Cannot overlap with Supervisor Cluster
   storage:
     #classes: ["gold", "silver"] #Named PVC storage classes
     defaultClass: cloud-storage