repoURL: https://gitlab.com/azwickey/tanzu-pez.git
targetRevision: HEAD
server: https://kubernetes.api.lb:6443  # This must be overridden
workload1:
  name: workload1
  namespace: demo
  kubernetesVersion: v1.18.5
  storage: cloud-storage
  controlPlaneCount: "1"
  controlPlaneClass: best-effort-medium
  workerCount: "1"
  workerClass: best-effort-xlarge