apiVersion: clusters.tmc.cloud.vmware.com/v1alpha1
kind: Extension
metadata:
  name: harbor
  namespace: tanzu-system-registry
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  description: harbor
  version: "v2.0.2_vmware.1"
  name: harbor
  namespace: tanzu-system-registry
  deploymentStrategy:
    type: KUBERNETES_NATIVE
  objects: |
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: harbor
      annotations:
        tmc.cloud.vmware.com/orphan-resource: "true"
    spec:
      syncPeriod: 5m
      serviceAccountName: harbor-extension-sa
      fetch:
        - image:
            url: registry.tkg.vmware.run/tkg-extensions-templates:v1.2.0_vmware.1
      template:
        - ytt:
            ignoreUnknownComments: true
            paths:
              - tkg-extensions/common
              - tkg-extensions/registry/harbor
            inline:
              paths:
                annotations-harbor.yaml: |
                  #@ load("@ytt:overlay", "overlay")
                  #@overlay/match by=overlay.subset({"kind": "Ingress", "metadata": {"name": "harbor-ingress"}})
                  ---
                  metadata:
                    #@overlay/match-child-defaults missing_ok=True
                    annotations: 
                      cert-manager.io/cluster-issuer: "letsencrypt-dns-cluster-issuer"
                  spec:
                    tls:
                      #@overlay/match by=overlay.index(0)
                      - secretName: harbor-tls-acme
                annotations-notary.yaml: |
                  #@ load("@ytt:overlay", "overlay")
                  #@overlay/match by=overlay.subset({"kind": "Ingress", "metadata": {"name": "harbor-ingress-notary"}})
                  ---
                  metadata:
                    #@overlay/match-child-defaults missing_ok=True
                    annotations: 
                      cert-manager.io/cluster-issuer: "letsencrypt-dns-cluster-issuer"
                  spec:
                    tls:
                      #@overlay/match by=overlay.index(0)
                      - secretName: notary-tls-acme
              pathsFrom:
                - secretRef:
                    name: harbor-data-values
      deploy:
        - kapp:
            rawOptions: ["--wait-timeout=5m"]
