apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-services-extensions-harbor
  namespace: argocd
  labels:
    cluster: {{ .Values.clusterName }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.server }}
  project: default
  syncPolicy:
    automated: {}
  source:
    path: cd/apps/extensions-harbor
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: domain
          value: "{{ .Values.harbor.domain }}"
        - name: commonPwd
          value: "{{ .Values.harbor.pwd }}"