apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-services-tbs-images
  namespace: argocd
  labels:
    cluster: {{ .Values.clusterName }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.server }}
  project: default
  # syncPolicy:
  #   automated: {} #Can't automate because it seems like KP gets into a bad state
  source:
    path: cd/apps/tbs-demo-images
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: harbor.domain
          value: "{{ .Values.harbor.domain }}"
        - name: repo
          value: "{{ .Values.harbor.domain }}"